/**
 * Types for OEM Catalyst Database (Bosal) — ECS component rows + companion sheets.
 * JSON is generated by scripts/import-oem-catalyst-database.py from the Excel workbook (V4+ includes source traceability).
 */

export interface EcsComponentRecord {
  oemGroup: string | null;
  brand: string | null;
  engineFamily: string | null;
  engineCodes: string | null;
  fuel: string | null;
  displacementL: number | string | null;
  cylinders: number | string | null;
  powerKw: string | null;
  emissionStandard: string | null;
  years: string | null;
  vehicleExamples: string | null;
  productionVolumeEu: string | null;
  componentNumber: string | null;
  componentType: string | null;
  position: string | null;
  substrate: string | null;
  substrateSupplier: string | null;
  diameterMm: number | string | null;
  lengthMm: number | string | null;
  volumeL: number | string | null;
  cpsi: number | string | null;
  wallMil: number | string | null;
  geometricSaM2PerL: number | string | null;
  ofaPercent: number | string | null;
  wcLayers: number | string | null;
  wcTotalGPerL: number | string | null;
  l1Support: string | null;
  l1SaM2PerG: number | string | null;
  l1Stabiliser: string | null;
  l1Promoter: string | null;
  l1OscMaterial: string | null;
  l1OscComposition: string | null;
  l1OscGPerL: number | string | null;
  l1Pgm: string | null;
  l1Extra: string | null;
  l1WcGPerL: number | string | null;
  l2Support: string | null;
  l2SaM2PerG: number | string | null;
  l2Stabiliser: string | null;
  l2Promoter: string | null;
  l2OscMaterial: string | null;
  l2OscComposition: string | null;
  l2OscGPerL: number | string | null;
  l2Pgm: string | null;
  l2Extra: string | null;
  l2WcGPerL: number | string | null;
  totalOscGPerL: number | string | null;
  ptGPerL: number | string | null;
  pdGPerL: number | string | null;
  rhGPerL: number | string | null;
  totalPgmGPerL: number | string | null;
  ptGPerBrick: number | string | null;
  pdGPerBrick: number | string | null;
  rhGPerBrick: number | string | null;
  t50CoC: number | string | null;
  t50HcC: number | string | null;
  t50NoxC: number | string | null;
  maxExoC: number | string | null;
  bpAtRatedKpa: number | string | null;
  agingProtocol: string | null;
  trend: string | null;
  confidence: string | null;
  source: string | null;
  /** Section heading from Excel (e.g. "VW Group") when present */
  sheetSection?: string | null;
}

export interface OemDatabaseManifest {
  databaseVersion: string;
  sourceFile: string;
  generatedAt: string;
  counts: {
    ecsComponents: number;
    washcoatChemistry: number;
    amDesignGuidance: number;
    ptPdSubstitution: number;
    systemArchitecture: number;
    /** Present from workbook V4 onward ("Source Traceability" sheet) */
    sourceTraceability?: number;
  };
  description: string;
}

/** Loose row shape for washcoat / architecture / Pt-Pd sheets (keys from Excel headers). */
export type OemReferenceRow = Record<string, string | number | null | undefined>;

export interface AmDesignGuidanceRow {
  parameter: string | null;
  oem_fresh__cc_brick?: string | null;
  oem_fresh__gpf?: string | null;
  oem_aged_160k_km?: string | null;
  am_fresh_target?: string | null;
  rationale?: string | null;
  test_method?: string | null;
  risk_if_wrong?: string | null;
}
